import type { MSME, Program, DashboardStats, AuditLogEntry, User } from './types';

export const MOCK_USER: User = {
  id: 'user-1',
  name: 'Sarah Kila',
  email: 'sarah.kila@smec.gov.pg',
  role: 'smec_officer',
  isActive: true,
};

export const MOCK_MSMES: MSME[] = [
  {
    id: 'msme-001',
    registrationNumber: 'SMEC-2025-00001',
    businessName: 'Highlands Fresh Produce Ltd',
    tradingName: 'Highlands Fresh',
    ownershipType: 'company',
    dateEstablished: '2018-03-15',
    registrationDate: '2025-01-15',
    ipaNumber: 'IPA-2018-45632',
    ircNumber: 'IRC-456321',
    tinNumber: 'TIN-789456123',
    smecMembershipNumber: 'SMEC-M-2025-001',
    sectorId: 'agriculture',
    sectorName: 'Agriculture, Forestry & Fishing',
    subSectorId: 'vegetables',
    subSectorName: 'Vegetables & Fruits',
    productsServices: ['Fresh vegetables', 'Organic produce', 'Supply to supermarkets'],
    businessSize: 'small',
    annualRevenue: 450000,
    employeeCount: 12,
    primaryPhone: '+675 7123 4567',
    email: 'info@highlandsfresh.pg',
    location: {
      provinceId: 'western-highlands',
      districtId: 'mount-hagen',
      llg: 'Mount Hagen Urban',
      village: 'Kagamuga',
      streetAddress: 'Lot 15, Airport Road',
    },
    owners: [
      {
        id: 'owner-001',
        fullName: 'Mary Kuman',
        gender: 'female',
        dateOfBirth: '1985-06-20',
        phone: '+675 7123 4567',
        email: 'mary@highlandsfresh.pg',
        ownershipPercentage: 60,
        isYouth: false,
        isPWD: false,
        idType: 'national_id',
        idNumber: 'NID-456789',
      },
      {
        id: 'owner-002',
        fullName: 'John Kuman',
        gender: 'male',
        dateOfBirth: '1982-09-10',
        phone: '+675 7123 4568',
        ownershipPercentage: 40,
        isYouth: false,
        isPWD: false,
      },
    ],
    womenOwnershipPercentage: 60,
    youthOwnershipPercentage: 0,
    pwdOwnershipPercentage: 0,
    isWomenLed: true,
    isYouthLed: false,
    hasPWDOwnership: false,
    greenProfile: {
      hasGreenProducts: true,
      greenProductsDescription: 'Organic farming practices, no chemical pesticides',
      energySource: 'solar',
      wasteManagement: 'recycling',
      waterManagement: 'conservation',
      climateRiskExposure: 'medium',
      greenCategory: 'green_ready',
      greenScore: 78,
      lastAssessmentDate: '2025-01-10',
    },
    hasBankAccount: true,
    bankName: 'BSP',
    accountType: 'business',
    documents: [
      {
        id: 'doc-001',
        type: 'ipa_certificate',
        name: 'IPA Certificate',
        url: '/docs/ipa-cert.pdf',
        uploadedAt: '2025-01-15',
        verifiedAt: '2025-01-16',
        verifiedBy: 'Admin User',
        status: 'verified',
      },
    ],
    status: 'active',
    verificationDate: '2025-01-16',
    verifiedBy: 'Sarah Kila',
    lastUpdated: '2025-01-20',
    needsAssessment: {
      financeNeed: true,
      financeAmount: 100000,
      financeType: 'expansion',
      marketAccessNeed: true,
      marketAccessType: 'national',
      skillsTrainingNeed: true,
      skillsTrainingAreas: ['Financial management', 'Export procedures'],
      equipmentNeed: true,
      equipmentType: 'Cold storage facility',
      technologyNeed: false,
    },
    programParticipations: [
      {
        programId: 'prog-001',
        programName: 'SMEC Business Growth Program',
        enrollmentDate: '2025-01-20',
        status: 'active',
      },
    ],
    financeReferrals: [
      {
        id: 'fin-001',
        institutionName: 'National Development Bank',
        productType: 'loan',
        amount: 100000,
        referralDate: '2025-01-25',
        status: 'in_progress',
        readinessRating: 'ready',
      },
    ],
    dataConsentGiven: true,
    dataConsentDate: '2025-01-15',
    marketingConsentGiven: true,
    createdAt: '2025-01-15T10:00:00Z',
    createdBy: 'admin',
    updatedAt: '2025-01-20T14:30:00Z',
    updatedBy: 'sarah.kila',
  },
  {
    id: 'msme-002',
    registrationNumber: 'SMEC-2025-00002',
    businessName: 'Pacific Blue Fisheries',
    ownershipType: 'partnership',
    dateEstablished: '2020-07-01',
    registrationDate: '2025-01-18',
    sectorId: 'agriculture',
    sectorName: 'Agriculture, Forestry & Fishing',
    subSectorId: 'fisheries',
    subSectorName: 'Fisheries & Aquaculture',
    productsServices: ['Fresh fish', 'Smoked fish', 'Seafood supply'],
    businessSize: 'micro',
    employeeCount: 5,
    primaryPhone: '+675 7234 5678',
    email: 'pacificblue@gmail.com',
    location: {
      provinceId: 'milne-bay',
      village: 'Alotau',
    },
    owners: [
      {
        id: 'owner-003',
        fullName: 'Peter Morea',
        gender: 'male',
        phone: '+675 7234 5678',
        ownershipPercentage: 50,
        isYouth: true,
        isPWD: false,
      },
      {
        id: 'owner-004',
        fullName: 'Anna Morea',
        gender: 'female',
        phone: '+675 7234 5679',
        ownershipPercentage: 50,
        isYouth: true,
        isPWD: false,
      },
    ],
    womenOwnershipPercentage: 50,
    youthOwnershipPercentage: 100,
    pwdOwnershipPercentage: 0,
    isWomenLed: false,
    isYouthLed: true,
    hasPWDOwnership: false,
    greenProfile: {
      hasGreenProducts: false,
      energySource: 'diesel',
      wasteManagement: 'basic',
      waterManagement: 'none',
      climateRiskExposure: 'high',
      greenCategory: 'emerging',
      greenScore: 32,
    },
    hasBankAccount: true,
    bankName: 'Westpac',
    accountType: 'savings',
    mobileMoneyProvider: 'Digicel MoniPlus',
    documents: [],
    status: 'submitted',
    lastUpdated: '2025-01-18',
    programParticipations: [],
    financeReferrals: [],
    dataConsentGiven: true,
    dataConsentDate: '2025-01-18',
    marketingConsentGiven: false,
    createdAt: '2025-01-18T09:00:00Z',
    createdBy: 'self-registration',
    updatedAt: '2025-01-18T09:00:00Z',
    updatedBy: 'self-registration',
  },
  {
    id: 'msme-003',
    registrationNumber: 'SMEC-2025-00003',
    businessName: 'Kokopo Eco Tours',
    tradingName: 'Kokopo Adventures',
    ownershipType: 'company',
    dateEstablished: '2019-05-20',
    registrationDate: '2025-01-20',
    ipaNumber: 'IPA-2019-78945',
    sectorId: 'tourism',
    sectorName: 'Tourism & Hospitality',
    productsServices: ['Eco-tourism', 'Cultural tours', 'Diving packages', 'WWII history tours'],
    businessSize: 'small',
    annualRevenue: 320000,
    employeeCount: 8,
    primaryPhone: '+675 7345 6789',
    email: 'info@kokopoecotours.pg',
    website: 'www.kokopoecotours.pg',
    location: {
      provinceId: 'east-new-britain',
      districtId: 'kokopo',
      streetAddress: 'Beach Road, Kokopo',
    },
    owners: [
      {
        id: 'owner-005',
        fullName: 'David ToLiman',
        gender: 'male',
        phone: '+675 7345 6789',
        ownershipPercentage: 70,
        isYouth: false,
        isPWD: false,
      },
      {
        id: 'owner-006',
        fullName: 'Grace ToLiman',
        gender: 'female',
        phone: '+675 7345 6790',
        ownershipPercentage: 30,
        isYouth: false,
        isPWD: false,
      },
    ],
    womenOwnershipPercentage: 30,
    youthOwnershipPercentage: 0,
    pwdOwnershipPercentage: 0,
    isWomenLed: false,
    isYouthLed: false,
    hasPWDOwnership: false,
    greenProfile: {
      hasGreenProducts: true,
      greenProductsDescription: 'Eco-friendly tourism, marine conservation programs',
      energySource: 'solar',
      wasteManagement: 'comprehensive',
      waterManagement: 'conservation',
      climateRiskExposure: 'high',
      greenCategory: 'green_certified',
      greenScore: 92,
      lastAssessmentDate: '2025-01-15',
    },
    hasBankAccount: true,
    bankName: 'ANZ',
    accountType: 'business',
    documents: [
      {
        id: 'doc-002',
        type: 'ipa_certificate',
        name: 'IPA Certificate',
        url: '/docs/ipa-kokopo.pdf',
        uploadedAt: '2025-01-20',
        status: 'pending',
      },
    ],
    status: 'under_review',
    lastUpdated: '2025-01-22',
    programParticipations: [],
    financeReferrals: [],
    dataConsentGiven: true,
    dataConsentDate: '2025-01-20',
    marketingConsentGiven: true,
    createdAt: '2025-01-20T11:00:00Z',
    createdBy: 'admin',
    updatedAt: '2025-01-22T10:00:00Z',
    updatedBy: 'admin',
  },
  {
    id: 'msme-004',
    registrationNumber: 'SMEC-2025-00004',
    businessName: 'Lae Coffee Roasters',
    ownershipType: 'sole_proprietor',
    dateEstablished: '2021-02-14',
    registrationDate: '2025-01-22',
    sectorId: 'manufacturing',
    sectorName: 'Manufacturing',
    subSectorId: 'food-processing',
    subSectorName: 'Food Processing',
    productsServices: ['Roasted coffee beans', 'Ground coffee', 'Specialty blends'],
    businessSize: 'micro',
    annualRevenue: 85000,
    employeeCount: 3,
    primaryPhone: '+675 7456 7890',
    email: 'laecoffeeroasters@gmail.com',
    location: {
      provinceId: 'morobe',
      districtId: 'lae',
      streetAddress: 'Industrial Area, Section 11',
    },
    owners: [
      {
        id: 'owner-007',
        fullName: 'Janet Suwae',
        gender: 'female',
        dateOfBirth: '1992-11-05',
        phone: '+675 7456 7890',
        ownershipPercentage: 100,
        isYouth: true,
        isPWD: false,
      },
    ],
    womenOwnershipPercentage: 100,
    youthOwnershipPercentage: 100,
    pwdOwnershipPercentage: 0,
    isWomenLed: true,
    isYouthLed: true,
    hasPWDOwnership: false,
    greenProfile: {
      hasGreenProducts: true,
      greenProductsDescription: 'Sources from organic highlands coffee farmers',
      energySource: 'grid',
      wasteManagement: 'recycling',
      waterManagement: 'basic',
      climateRiskExposure: 'low',
      greenCategory: 'transitioning',
      greenScore: 58,
    },
    hasBankAccount: true,
    bankName: 'BSP',
    accountType: 'savings',
    mobileMoneyProvider: 'BSP Mobile',
    documents: [],
    status: 'verified',
    verificationDate: '2025-01-25',
    verifiedBy: 'Provincial Officer',
    lastUpdated: '2025-01-25',
    needsAssessment: {
      financeNeed: true,
      financeAmount: 50000,
      financeType: 'equipment',
      marketAccessNeed: true,
      marketAccessType: 'export',
      skillsTrainingNeed: true,
      skillsTrainingAreas: ['Export certification', 'Quality control'],
      equipmentNeed: true,
      equipmentType: 'Commercial coffee roaster',
      technologyNeed: true,
      technologyType: 'E-commerce platform',
    },
    programParticipations: [],
    financeReferrals: [],
    dataConsentGiven: true,
    dataConsentDate: '2025-01-22',
    marketingConsentGiven: true,
    createdAt: '2025-01-22T14:00:00Z',
    createdBy: 'admin',
    updatedAt: '2025-01-25T16:00:00Z',
    updatedBy: 'provincial_officer',
  },
  {
    id: 'msme-005',
    registrationNumber: 'SMEC-2025-00005',
    businessName: 'Port Moresby Construction Supplies',
    tradingName: 'POM Build',
    ownershipType: 'company',
    dateEstablished: '2015-08-10',
    registrationDate: '2025-01-25',
    ipaNumber: 'IPA-2015-12345',
    ircNumber: 'IRC-123456',
    tinNumber: 'TIN-987654321',
    sectorId: 'wholesale-retail',
    sectorName: 'Wholesale & Retail Trade',
    subSectorId: 'hardware',
    subSectorName: 'Hardware & Building Materials',
    productsServices: ['Building materials', 'Hardware supplies', 'Construction equipment rental'],
    businessSize: 'medium',
    annualRevenue: 2500000,
    employeeCount: 35,
    primaryPhone: '+675 321 4567',
    secondaryPhone: '+675 321 4568',
    email: 'sales@pombuild.pg',
    website: 'www.pombuild.pg',
    location: {
      provinceId: 'ncd',
      districtId: 'ncd-south',
      streetAddress: 'Lot 5, Badili Industrial Estate',
      postalCode: '121',
    },
    owners: [
      {
        id: 'owner-008',
        fullName: 'Michael Vele',
        gender: 'male',
        phone: '+675 7567 8901',
        ownershipPercentage: 60,
        isYouth: false,
        isPWD: false,
      },
      {
        id: 'owner-009',
        fullName: 'Thomas Vele',
        gender: 'male',
        phone: '+675 7567 8902',
        ownershipPercentage: 40,
        isYouth: false,
        isPWD: true,
      },
    ],
    womenOwnershipPercentage: 0,
    youthOwnershipPercentage: 0,
    pwdOwnershipPercentage: 40,
    isWomenLed: false,
    isYouthLed: false,
    hasPWDOwnership: true,
    greenProfile: {
      hasGreenProducts: false,
      energySource: 'grid',
      wasteManagement: 'basic',
      waterManagement: 'none',
      climateRiskExposure: 'low',
      greenCategory: 'emerging',
      greenScore: 25,
    },
    hasBankAccount: true,
    bankName: 'Kina Bank',
    accountType: 'business',
    documents: [
      {
        id: 'doc-003',
        type: 'ipa_certificate',
        name: 'IPA Certificate',
        url: '/docs/ipa-pombuild.pdf',
        uploadedAt: '2025-01-25',
        verifiedAt: '2025-01-26',
        verifiedBy: 'Admin',
        status: 'verified',
      },
      {
        id: 'doc-004',
        type: 'tin_certificate',
        name: 'TIN Certificate',
        url: '/docs/tin-pombuild.pdf',
        uploadedAt: '2025-01-25',
        verifiedAt: '2025-01-26',
        verifiedBy: 'Admin',
        status: 'verified',
      },
    ],
    status: 'active',
    verificationDate: '2025-01-26',
    verifiedBy: 'Sarah Kila',
    lastUpdated: '2025-01-28',
    programParticipations: [],
    financeReferrals: [],
    dataConsentGiven: true,
    dataConsentDate: '2025-01-25',
    marketingConsentGiven: true,
    createdAt: '2025-01-25T09:00:00Z',
    createdBy: 'admin',
    updatedAt: '2025-01-28T11:00:00Z',
    updatedBy: 'sarah.kila',
  },
  {
    id: 'msme-006',
    registrationNumber: 'SMEC-2025-00006',
    businessName: 'Goroka Bilum Weavers Cooperative',
    ownershipType: 'cooperative',
    dateEstablished: '2017-04-12',
    registrationDate: '2025-01-28',
    sectorId: 'crafts',
    sectorName: 'Handicrafts & Artifacts',
    productsServices: ['Traditional bilums', 'Custom woven bags', 'Cultural crafts'],
    businessSize: 'small',
    annualRevenue: 180000,
    employeeCount: 45,
    primaryPhone: '+675 7678 9012',
    email: 'gorokabilum@gmail.com',
    location: {
      provinceId: 'eastern-highlands',
      districtId: 'goroka',
      village: 'Goroka Town',
    },
    owners: [
      {
        id: 'owner-010',
        fullName: 'Esther Gena',
        gender: 'female',
        phone: '+675 7678 9012',
        ownershipPercentage: 25,
        isYouth: false,
        isPWD: false,
      },
      {
        id: 'owner-011',
        fullName: 'Rebecca Mondo',
        gender: 'female',
        phone: '+675 7678 9013',
        ownershipPercentage: 25,
        isYouth: false,
        isPWD: false,
      },
      {
        id: 'owner-012',
        fullName: 'Martha Kila',
        gender: 'female',
        phone: '+675 7678 9014',
        ownershipPercentage: 25,
        isYouth: true,
        isPWD: false,
      },
      {
        id: 'owner-013',
        fullName: 'Lucy Sinaka',
        gender: 'female',
        phone: '+675 7678 9015',
        ownershipPercentage: 25,
        isYouth: false,
        isPWD: true,
      },
    ],
    womenOwnershipPercentage: 100,
    youthOwnershipPercentage: 25,
    pwdOwnershipPercentage: 25,
    isWomenLed: true,
    isYouthLed: false,
    hasPWDOwnership: true,
    greenProfile: {
      hasGreenProducts: true,
      greenProductsDescription: 'Natural dyes, sustainable materials, traditional methods',
      energySource: 'none',
      wasteManagement: 'recycling',
      waterManagement: 'conservation',
      climateRiskExposure: 'medium',
      greenCategory: 'green_ready',
      greenScore: 85,
    },
    hasBankAccount: true,
    bankName: 'BSP',
    accountType: 'savings',
    documents: [],
    status: 'submitted',
    lastUpdated: '2025-01-28',
    programParticipations: [
      {
        programId: 'prog-002',
        programName: 'Women in Business Program',
        enrollmentDate: '2024-06-15',
        status: 'completed',
        completionDate: '2024-12-15',
      },
    ],
    financeReferrals: [],
    dataConsentGiven: true,
    dataConsentDate: '2025-01-28',
    marketingConsentGiven: true,
    createdAt: '2025-01-28T13:00:00Z',
    createdBy: 'self-registration',
    updatedAt: '2025-01-28T13:00:00Z',
    updatedBy: 'self-registration',
  },
];

export const MOCK_PROGRAMS: Program[] = [
  {
    id: 'prog-001',
    name: 'SMEC Business Growth Program',
    description: 'Comprehensive business development program for established SMEs looking to scale operations.',
    type: 'incubation',
    provider: 'SMEC',
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    status: 'active',
    maxParticipants: 50,
    currentParticipants: 23,
    isFocusedOnWomen: false,
    isFocusedOnYouth: false,
    isFocusedOnGreen: true,
  },
  {
    id: 'prog-002',
    name: 'Women in Business Program',
    description: 'Targeted support for women-led enterprises including mentorship, training, and market linkages.',
    type: 'mentorship',
    provider: 'SMEC / UN Women',
    startDate: '2024-01-01',
    endDate: '2025-06-30',
    status: 'active',
    maxParticipants: 100,
    currentParticipants: 78,
    isFocusedOnWomen: true,
    isFocusedOnYouth: false,
    isFocusedOnGreen: false,
  },
  {
    id: 'prog-003',
    name: 'Climate FIRST Green Enterprise Fund',
    description: 'Grant program for MSMEs adopting climate-smart practices and green technologies.',
    type: 'grant',
    provider: 'GGGI / DFAT',
    startDate: '2025-03-01',
    endDate: '2027-02-28',
    status: 'planned',
    targetSectors: ['agriculture', 'energy', 'manufacturing'],
    maxParticipants: 200,
    currentParticipants: 0,
    isFocusedOnWomen: false,
    isFocusedOnYouth: false,
    isFocusedOnGreen: true,
  },
  {
    id: 'prog-004',
    name: 'Youth Enterprise Development',
    description: 'Startup support and business skills training for young entrepreneurs under 35.',
    type: 'training',
    provider: 'SMEC / ILO',
    startDate: '2025-02-01',
    endDate: '2025-08-31',
    status: 'active',
    maxParticipants: 150,
    currentParticipants: 45,
    isFocusedOnWomen: false,
    isFocusedOnYouth: true,
    isFocusedOnGreen: false,
  },
  {
    id: 'prog-005',
    name: 'Export Ready Program',
    description: 'Technical assistance for MSMEs seeking to enter international markets.',
    type: 'technical_assistance',
    provider: 'SMEC / Trade PNG',
    startDate: '2025-01-15',
    endDate: '2025-12-15',
    status: 'active',
    targetSectors: ['agriculture', 'manufacturing', 'crafts'],
    maxParticipants: 30,
    currentParticipants: 12,
    isFocusedOnWomen: false,
    isFocusedOnYouth: false,
    isFocusedOnGreen: false,
  },
];

export const MOCK_AUDIT_LOG: AuditLogEntry[] = [
  {
    id: 'log-001',
    msmeId: 'msme-001',
    action: 'created',
    userId: 'admin',
    userName: 'System Admin',
    timestamp: '2025-01-15T10:00:00Z',
  },
  {
    id: 'log-002',
    msmeId: 'msme-001',
    action: 'status_changed',
    field: 'status',
    oldValue: 'draft',
    newValue: 'submitted',
    userId: 'admin',
    userName: 'System Admin',
    timestamp: '2025-01-15T10:30:00Z',
  },
  {
    id: 'log-003',
    msmeId: 'msme-001',
    action: 'verified',
    field: 'status',
    oldValue: 'submitted',
    newValue: 'active',
    userId: 'sarah.kila',
    userName: 'Sarah Kila',
    timestamp: '2025-01-16T14:00:00Z',
  },
  {
    id: 'log-004',
    msmeId: 'msme-001',
    action: 'program_enrolled',
    newValue: 'SMEC Business Growth Program',
    userId: 'sarah.kila',
    userName: 'Sarah Kila',
    timestamp: '2025-01-20T09:00:00Z',
  },
];

export const MOCK_DASHBOARD_STATS: DashboardStats = {
  totalMSMEs: 1247,
  activeMSMEs: 892,
  pendingVerification: 156,
  newThisMonth: 47,
  bySize: {
    micro: 687,
    small: 423,
    medium: 137,
  },
  byStatus: {
    draft: 89,
    submitted: 112,
    under_review: 44,
    verified: 110,
    active: 892,
    suspended: 0,
    inactive: 0,
  },
  womenLedCount: 312,
  youthLedCount: 189,
  pwdOwnershipCount: 45,
  greenReadyCount: 234,
  byProvince: [
    { provinceId: 'ncd', provinceName: 'National Capital District', count: 287 },
    { provinceId: 'morobe', provinceName: 'Morobe', count: 198 },
    { provinceId: 'western-highlands', provinceName: 'Western Highlands', count: 156 },
    { provinceId: 'eastern-highlands', provinceName: 'Eastern Highlands', count: 134 },
    { provinceId: 'east-new-britain', provinceName: 'East New Britain', count: 98 },
    { provinceId: 'madang', provinceName: 'Madang', count: 87 },
    { provinceId: 'chimbu', provinceName: 'Chimbu (Simbu)', count: 65 },
    { provinceId: 'enga', provinceName: 'Enga', count: 54 },
    { provinceId: 'milne-bay', provinceName: 'Milne Bay', count: 48 },
    { provinceId: 'central', provinceName: 'Central', count: 42 },
  ],
  bySector: [
    { sectorId: 'wholesale-retail', sectorName: 'Wholesale & Retail Trade', count: 356 },
    { sectorId: 'agriculture', sectorName: 'Agriculture, Forestry & Fishing', count: 287 },
    { sectorId: 'accommodation-food', sectorName: 'Accommodation & Food Services', count: 178 },
    { sectorId: 'manufacturing', sectorName: 'Manufacturing', count: 134 },
    { sectorId: 'transport', sectorName: 'Transport & Logistics', count: 98 },
    { sectorId: 'professional', sectorName: 'Professional Services', count: 76 },
    { sectorId: 'construction', sectorName: 'Construction', count: 54 },
    { sectorId: 'crafts', sectorName: 'Handicrafts & Artifacts', count: 34 },
    { sectorId: 'tourism', sectorName: 'Tourism & Hospitality', count: 30 },
  ],
  financeNeedTotal: 523,
  programEnrollments: 158,
};
